### ISSUE TITLE
Lilypads spawn in any water regardless of biome (1.20.1)

### ISSUE THREAD

**Issue by StonkseleksI** [AelveMC/SEP_1_Renewables#5] opened 2024-08-21 02:30 UTC
Noticed the armor stand sound happened no matter what biome I was in, lo and behold, spawned lilypads in a river biome

**Comment by AelveMC** [comment] 2024-08-24 11:06
I can't reproduce the issue in 1.20.1 with either the 1.2 or 1.3 versions of the datapack. Maybe you have something conflicting with it? Try it on a different vanilla world with no other datapacks and see if it persists.

**Comment by StonkseleksI** [comment] 2024-08-24 19:32
I was using version 1.5, and my sincerest apologies, I'm so used to playing 1.20.1 that I mistyped it. I'm playing on 1.21.0, here's a clip.

https://github.com/user-attachments/assets/23e7fb7e-f340-4058-b1a9-c7ab909d0132

**Comment by AelveMC** [comment] 2024-08-25 02:21
Haha, no worries. Thanks for the report, that should be fixed in the 1.6 version.

**Closed as completed by AelveMC** 2024-08-25 02:21 UTC
